# Generated by Django 3.2 on 2022-04-29 10:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
