# Generated by Django 3.2 on 2022-04-29 10:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0002_alter_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(),
        ),
    ]
