# Generated by Django 3.2 on 2022-05-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port_app', '0002_auto_20220512_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_approve',
        ),
    ]
